name: Tested ApkEdit decompile res

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

  ##  - name: Run Apk Edit
  ##   run: chmod +x gradlew
    - name: Run
      run: java -jar ./APKEditor-1.4.2.jar info -v -resources -i ./HeroTale134modBedo13.apk >>./test_json
    - name: Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Save-Result
        path: |
               ./*
