name: Tested ApkEdit decompile res

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Apk Edit
      run: chmod +x gradlew
    - name: Run
      run: java -jar ./APKEditor-1.4.2.jar d -i ./resources.arsc -o test_json
      
    - uses: actions/upload-artifact@v4
      with:
        name: Save-Result
        path: |
               /*
